name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8 mypy pylint bandit safety
        pip install pytest-asyncio
    - name: Run linters and checks
      run: |
        black --check .
        isort --check-only .
        flake8 .
        mypy .
        pylint **/*.py
        bandit -r . -f custom
        safety check
    - name: Check documentation build
      run: |
        pip install sphinx sphinx_rtd_theme
        cd docs && make html
    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings tests/
    - name: Run tests with pytest-asyncio
      run: pytest --asyncio-mode=auto --maxfail=1 --disable-warnings tests/
    - name: Check for sensitive data
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
